<?

$langrep = array(
"title"					=>	'SignalTracker',
"pagedescription"		=>	'Veja o mapa de cobertura de sua operadora e contribua!',
"pagekeywords"			=>	'SignalTracker, Signal, Tracker, Signal Tracker, VIVO, CLARO, OI, TIM, ANATEL, Operadoras, Celulares, Sinal, Cobertura',
"companyname"			=>	'Teske Virtual System Ltda. - ME',
"homefirstmsg"			=> '<strong>Signal Tracker</strong> &eacute; um projeto voltado para comunidade onde seu objetivo principal &eacute; fazer um mapeamento da cobertura das operadoras de telefonia celular. Como os dados de cobertura informados pelas operadoras s&atilde;o suspeitos este projeto visa a contribui&ccedil;&atilde;o da comunidade com informa&ccedil;&otilde;es sobre a cobertura na &aacute;rea onde vive.',
"homesecondmsg"			=> 'Para contribuir com o <strong>Signal Tracker</strong> &eacute; muito simples! O requisito b&aacute;sico &eacute; ter um celular <strong>Android 2.3.3</strong> ou superior e instalar o aplicativo <strong>Signal Tracker</strong> que se encontra no <strong><a href="https://play.google.com/store/apps/details?id=com.mobilles.signalsampler">Google Play</a></strong>, ou pelo <strong>QRCode</strong> que pode ser encontrado no canto desta p&aacute;gina.<BR>      <a href="{SITEURL}page/sobre"><strong>Mais informa&ccedil;&otilde;es</strong></a>',
"howtocontribute"		=>	'Como contribuir?',
"whatis"				=>	'O que &eacute;?',
"formoreinfo"			=>	'Para ler mais sobre o projeto visite <a href="{SITEURL}page/about">Sobre &raquo; Sobre o Projeto</a>',
"systemconstruction"	=>	'Este sistema ainda est&aacute; em constru&ccedil;&atilde;o!',
"disablesignals"		=>	'Desativar Sinais',
"enablesignals"			=>	'Ativar Sinais',
"disableantennas"		=>	'Desativar Antenas',
"enableantennas"		=>	'Ativar Antenas',
"menu"					=>	'Menu',
"options"				=>	'Op&ccedil;&otilde;es',
"operators"				=>	'Operadoras',
"loadingoperators"		=>	'Carregando Operadoras',
"goto"					=>	'Ir para',
"notlogged"				=>	'Voc&ecirc; n&atilde;o efetuou o login!',
"usestatistics"			=>	'Estat&iacute;sticas de Uso do SignalTracker',
"monthgeneralgraph"		=>	'Gr&aacute;fico geral do m&circ;s atual',
"monthsignalgraph"		=>	'Gr&aacute;fico de sinais novos do m&circ;s atual',
"monthtowergraph"		=>	'Gr&aacute;fico de torres novas do m&ecirc;s atual',
"monthapigraph"			=>	'Gr&aacute;fico de chamadas na API do m&ecirc;s atual',
"monthttsgraph"			=>	'Gr&aacute;fico de chamadas do TeskeTrackingSystem do m&ecirc;s atual',
"testeddevices"			=>	'Aparelhos Testados',
"device"				=>	'Dispositivo',
"manufacturer"			=>	'Fabricante',
"model"					=>	'Modelo',
"brand"					=>	'Marca',
"android"				=>	'Android',
"bestcontributers"		=>	'Melhores Contribuidores',
"aboutproject"			=>	'Sobre o projeto',
"about"					=>	'Sobre',
"home"					=>	'Home',
"seecoverage"			=>	'Ver cobertura',
"all"					=>	'Todos',
"changingoperatorto"	=>	'Trocando operadora para',
"searchingaddress"		=>	'Procurando endere&ccedil;o',
"wecantfindaddress"		=>	'N&atilde;o pudemos achar seu endere&ccedi;o!',
"clickedin"				=>	'Clicado em',
"selectoperator"		=>	'Selecione a operadora',
"goingtohtmlloc"		=>	'Indo para localização determinada pelo HTML5',
"goingtodefaultloc"		=>	'Indo para localização padrão',
);

?>
